### PR TITLE
Simulations for 9 vs 13m trade study

### PR DESCRIPTION
**Pull request by dpesce**
This branch contains some simulations that provide metric values used in the 9m vs 13m trade study. Specifically, it quantifies the filling fraction for the full and monitoring arrays when observing M87 and Sgr A*, and it compares various potential variants of the array in terms of dish size, recording rate, and station choices.

### CODE REVIEW

**Comment by ryan-chaves-sao** [comment]
The new files look fine, although you need to address the [lint failures](https://github.com/Smithsonian/ngeht-arrayperformance-sims/actions/runs/7634617155/job/20798764314?pr=5).

I was going to suggest that these new simulations need to be added to the smoke test automation, but then I saw your note in `README.txt`:
> Note: The gendata.py script will take several hours to complete on a typical laptop or desktop.

If that would equally be the case for the environments in which the smoke tests run, then we should definitely **not** add these simulations to the smoke test suite!

**Comment by dpesce** [comment]
Okay, I've gone through and addressed a number of the linter's concerns.  As far as I can tell, the remaining things it gets hung up on are all of the "this line exceeds some number of characters" type, and in the case of these scripts it would actually hurt code readability to break up some of these lines.  So I've left them as-is.

Moving forward, can we turn off the linter throwing a "failed check" upon hitting issues like these?  Some issues like, e.g., "too many characters on a line," "extra line break at the end of the file," "no white space after a comma," "the import statement is not located at the top of the file," etc., are purely aesthetic preferences that have no bearing the actual functioning of the code.  And it doesn't feel like a good use of time to have to re-do pull requests that are constantly failing until the linter is satisfied that all of these non-critical items are resolved.  I'd rather we just have the linter throw a "failed check" when there's an actual error in the code.

**Comment by ryan-chaves-sao** [comment]
> Okay, I've gone through and addressed a number of the linter's concerns. As far as I can tell, the remaining things it gets hung up on are all of the "this line exceeds some number of characters" type, and in the case of these scripts it would actually hurt code readability to break up some of these lines. So I've left them as-is.
> 
> Moving forward, can we turn off the linter throwing a "failed check" upon hitting issues like these? Some issues like, e.g., "too many characters on a line," "extra line break at the end of the file," "no white space after a comma," "the import statement is not located at the top of the file," etc., are purely aesthetic preferences that have no bearing the actual functioning of the code. And it doesn't feel like a good use of time to have to re-do pull requests that are constantly failing until the linter is satisfied that all of these non-critical items are resolved. I'd rather we just have the linter throw a "failed check" when there's an actual error in the code.

Just a heads-up: I'm tied up with something so I may not be able to get back to this until early next week.

**Comment by wumpus** [comment]
You should be linting in your editor, so that you can see problems as you type.

Less effective, a "make lint" command you can run before checkin.

I use the flycheck plugin in emacs, every editor has something similar.

**Comment by ryan-chaves-sao** [comment]
@dpesce There are already a [number of lint errors and warnings that are purposefully ignored](https://github.com/Smithsonian/ngeht-arrayperformance-sims/blob/71defc5335c48c760d47772ecdd83aac30328200/.github/workflows/lint.yml#L22). These exceptions arose from past experience on Python development projects. So, it's certainly possible to add to this.

However, I think it would first be beneficial for you to read [PEP 8](https://peps.python.org/pep-0008/), the Python Style Guide, and particularly the section on [maximum line length](https://peps.python.org/pep-0008/#maximum-line-length). In general, coding standards and style guides exist to (a) improve readability and maintainability and (b) make the learning curve less steep for newcomers to the codebase by providing a familiar set of conventions for the structure and formatting of the code. What may seem to you like purely aesthetic preferences can actually be indications of potential future trouble (though, upon my re-read of PEP 8, I find it lacking in consistently providing rationale).

Regarding lint failures that you've mentioned:
> ... "too many characters on a line," ...

Please (a) review the first two sections of PEP 8 as well as the section on maximum line lengths and (b) point me to some examples of too-long lines that shouldn't be broken up. I'd like to walk through them to ultimately decide how to handle them.

> "extra line break at the end of the file," "no white space after a comma," "the import statement is not located at the top of the file," ...

These are easy to fix, though to @wumpus 's point I can see where it's annoying to be alerted to this only after you've pushed and waited for the lint action to run. His suggestion of adding auto-linting to your IDE is a good one. I can help you with that (or @wumpus if he's willing!). If you want to discuss the rationale for any of these, I'm happy to do so.

If you would like to address some of this in-person rather than through pull request conversation, I'm open to that. Just let me know!

**Comment by dpesce** [comment]
@ryan-chaves-sao @wumpus I appreciate you both taking the time to provide your thoughts here, but frankly, I think the fact that we've already gone multiple responses deep into this thread and delayed merging by >1 week is evidence of exactly the sort of waste of time + effort that I am hoping to avoid by simply turning off these linter preferences.

I think that I already have a general sense of the role that these sorts of linting choices serve in the broader software development community.  But this really is not a software development repository, and trying to treat it like one (e.g., requiring pull requests for every change, imposing this gatekeeping linter thing) has in practice just been a substantial additional source of inefficiency for me on top of my normal workflow.  While I've already had a conversation with Ryan about the benefits to traceability of using a pull request scheme (and thus I've agreed to adhere to that scheme), I don't think something similar applies to this micro-linting business; as far as I'm concerned, if the code functions (i.e., runs reproducibly) then it has done its job.

I remain of the opinion that the simplest and most efficient path forward for me would be if we could just turn off the current linter barrier.  If someone else wants to write a utility that automatically applies lint-recommended changes to the scripts upon a pull request, then that would be totally fine by me, but I do not consider it to be a worthwhile use of my (or anyone else's) time to micromanage whitespace or line lengths in this repository.

**Review by ryan-chaves-sao — APPROVED** [review]
Good to go now! 👍

**Pull request merged**
